# Import data sources
import yfinance as yf
import pandas as pd

# Define sector ETFs (you can add more)
sector_etfs = {
    'S&P 500': 'SPY'
    'NASDAQ': 'NDAQ'
    'DOW Jones': 'DJI'
    'Technology': 'XLK',
    'Healthcare': 'XLV',
    'Financials': 'XLF',
    'Energy': 'XLE',
    'Consumer Discretionary': 'XLY',
    'Consumer Staples': 'XLP',
    'Industrials': 'XLI',
    'Utilities': 'XLU',
    'Materials': 'XLB',
    'Real Estate': 'XLRE',
    'Communication': 'XLC'
}

# Fetch historical data
def get_sector_performance(etfs, period='7d'):
    data = {}
    for sector, ticker in etfs.items():
        hist = yf.Ticker(ticker).history(period=period)
        if not hist.empty:
            change = ((hist['Close'][-1] - hist['Close'][0]) / hist['Close'][0]) * 100
            data[sector] = round(change, 2)
    return pd.Series(data, name='Change (%)').sort_values(ascending=False)

performance = get_sector_performance(sector_etfs)
print(performance)
